### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can't load the profile.

### ISSUE THREAD

**Issue by giando** [mussaimo/github-bot#1]
Hello @mussaimo,
I get this error:
```python
Traceback (most recent call last):
  File "./follow_bot.py", line 8, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpKx2Fqn If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
Why?
Thank you and congratulations for the project! :wink::+1:

**Comment by mussaimo** [comment]
@giando 
For Firefox version 47.0, a new driver must be used (created by mozilla instead of selenium) to connect to Firefox, because of a bug introduces in this version.

I updated the code base to work with upcoming versions(47.0+) though I'm sure it will still need some tweaking in the future. Thank you for catching that error on time.
